<?php declare(strict_types=1);

namespace AdminBundle\Entity;

use AdminBundle\Entity\User;
use FOS\UserBundle\Doctrine\UserManager as BaseUserManager;
use FOS\UserBundle\Model\UserInterface;

class UserManager extends BaseUserManager
{
    /**
     * {@inheritdoc}
     *
     * @param UserInterface|User $user
     */
    public function updateUser(UserInterface $user, $andFlush = true)
    {
        if ($user->getResetApiKey()) {
            $user->doResetApiKey();
        }

        parent::updateUser($user, $andFlush); // TODO: Change the autogenerated stub
    }
}