datePublished:
    type: object
    config:
        fields:
            endDate:
                #type: "Int"
                type: "String"
            startDate:
                #type: "Int"
                type: "String"