fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security:
  resource: "@AdminBundle/Resources/config/routing/security.xml"

easy_admin_bundle:
  resource: "@AdminBundle/Controller/AdminController.php"
  type: annotation
  prefix: /dapadmin/admin
