services:
    app.user_manager:
        class: AdminBundle\Entity\UserManager
        arguments:
            - '@fos_user.util.password_updater'
            - '@fos_user.util.canonical_fields_updater'
            - '@fos_user.object_manager'
            - '%fos_user.model.user.class%'

    app.security.guard.api_key:
        class: AdminBundle\Security\Guard\ApiKeyGuardAuthenticator
        arguments:
            - '@app.user_manager'

