mainImage:
    type: object
    config:
        fields:
            small:
                type: String
            medium:
                type: String
            large:
                type: String